import React from "react";
import "./Menucard.css";

const Menucard = () => {
  const foodItems = [
    {
      _id: "1",
      name: "Idly Sambar",
      image: "food_1.jpg",
      price: 50,
      category: "South Indian",
    },
    {
      _id: "2",
      name: "Thatte Idly",
      image: "food_2.jpg",
      price: 60,
      category: "South Indian",
    },
    {
      _id: "3",
      name: "Rava Idly",
      image: "food_3.jpg",
      price: 55,
      category: "South Indian",
    },
    {
      _id: "4",
      name: "Masala Dosa",
      image: "food_4.jpg",
      price: 80,
      category: "South Indian",
    },
    {
      _id: "5",
      name: "Set Dosa",
      image: "food_5.jpg",
      price: 70,
      category: "South Indian",
    },
    {
      _id: "6",
      name: "Rava Dosa",
      image: "food_6.jpg",
      price: 70,
      category: "South Indian",
    },
    {
      _id: "7",
      name: "Vada",
      image: "food_7.jpg",
      price: 40,
      category: "South Indian",
    },
    {
      _id: "8",
      name: "Dahi Vada",
      image: "food_8.jpg",
      price: 55,
      category: "South Indian",
    },
    {
      _id: "9",
      name: "Onion Dosa",
      image: "food_9.jpg",
      price: 85,
      category: "South Indian",
    },
    {
      _id: "10",
      name: "Chow Chowbath",
      image: "food_10.jpg",
      price: 65,
      category: "South Indian",
    },
    {
      _id: "11",
      name: "Bisibelebath",
      image: "food_11.jpg",
      price: 70,
      category: "South Indian",
    },
    {
      _id: "12",
      name: "Upma",
      image: "food_12.jpg",
      price: 50,
      category: "South Indian",
    },
    {
      _id: "13",
      name: "Pongal",
      image: "food_13.jpg",
      price: 60,
      category: "South Indian",
    },
    {
      _id: "14",
      name: "Poori",
      image: "food_14.jpg",
      price: 55,
      category: "South Indian",
    },
    {
      _id: "15",
      name: "Curd Rice",
      image: "food_15.jpg",
      price: 50,
      category: "South Indian",
    },
    {
      _id: "16",
      name: "Mangalore Bonda",
      image: "food_16.jpg",
      price: 50,
      category: "South Indian",
    },
    {
      _id: "17",
      name: "Mangalore Buns",
      image: "food_17.jpg",
      price: 55,
      category: "South Indian",
    },
    {
      _id: "18",
      name: "Maddur Vada",
      image: "food_18.jpg",
      price: 50,
      category: "South Indian",
    },
    {
      _id: "19",
      name: "Chapathi",
      image: "food_19.jpg",
      price: 40,
      category: "South Indian",
    },
    {
      _id: "20",
      name: "Tomato Bath",
      image: "food_20.jpg",
      price: 70,
      category: "South Indian",
    },
    {
      _id: "21",
      name: "Pudina Bath",
      image: "food_21.jpg",
      price: 60,
      category: "South Indian",
    },
    {
      _id: "22",
      name: "Lemon Rice",
      image: "food_22.jpg",
      price: 55,
      category: "South Indian",
    },
    {
      _id: "23",
      name: "Vangi Bath",
      image: "food_23.jpg",
      price: 65,
      category: "South Indian",
    },
    {
      _id: "24",
      name: "Rice Sambhar",
      image: "food_24.jpg",
      price: 75,
      category: "South Indian",
    },
    {
      _id: "25",
      name: "Coconut Rice",
      image: "food_25.jpg",
      price: 60,
      category: "South Indian",
    },
    {
      _id: "26",
      name: "Puliyogare",
      image: "food_26.jpg",
      price: 60,
      category: "South Indian",
    },
    {
      _id: "27",
      name: "Bonda Soup",
      image: "food_27.jpg",
      price: 60,
      category: "South Indian",
    },
    {
      _id: "28",
      name: "South Meals",
      image: "food_28.jpg",
      price: 120,
      category: "South Indian",
    },
    {
      _id: "29",
      name: "Kulcha",
      image: "food_29.jpg",
      price: 70,
      category: "North Indian",
    },
    {
      _id: "30",
      name: "Roti",
      image: "food_30.jpg",
      price: 40,
      category: "North Indian",
    },
    {
      _id: "31",
      name: "Naan",
      image: "food_31.jpg",
      price: 60,
      category: "North Indian",
    },
    {
      _id: "32",
      name: "Naan Curry",
      image: "food_32.jpg",
      price: 120,
      category: "North Indian",
    },
    {
      _id: "33",
      name: "Roti Curry",
      image: "food_33.jpg",
      price: 100,
      category: "North Indian",
    },
    {
      _id: "34",
      name: "Paneer Paratha",
      image: "food_34.jpg",
      price: 90,
      category: "North Indian",
    },
    {
      _id: "35",
      name: "Paratha",
      image: "food_35.jpg",
      price: 70,
      category: "North Indian",
    },
    {
      _id: "36",
      name: "Aloo Paratha",
      image: "food_36.jpg",
      price: 80,
      category: "North Indian",
    },
    {
      _id: "37",
      name: "Aloo Gobi Masala",
      image: "food_37.jpg",
      price: 100,
      category: "North Indian",
    },
    {
      _id: "38",
      name: "Aloo Masala",
      image: "food_38.jpg",
      price: 100,
      category: "North Indian",
    },
    {
      _id: "39",
      name: "Aloo Matar Masala",
      image: "food_39.jpg",
      price: 130,
      category: "North Indian",
    },
    {
      _id: "40",
      name: "Chana Masala",
      image: "food_40.jpg",
      price: 120,
      category: "North Indian",
    },
    {
      _id: "41",
      name: "Chole Bhature",
      image: "food_41.jpg",
      price: 150,
      category: "North Indian",
    },
    {
      _id: "42",
      name: "Dal Tadka",
      image: "food_42.jpg",
      price: 100,
      category: "North Indian",
    },
    {
      _id: "43",
      name: "Dal Khichdi",
      image: "food_43.jpg",
      price: 90,
      category: "North Indian",
    },
    {
      _id: "44",
      name: "Dum Aloo",
      image: "food_44.jpg",
      price: 150,
      category: "North Indian",
    },
    {
      _id: "45",
      name: "Shahi Paneer",
      image: "food_45.jpg",
      price: 190,
      category: "North Indian",
    },
    {
      _id: "46",
      name: "Kadai Paneer",
      image: "food_46.jpg",
      price: 180,
      category: "North Indian",
    },
    {
      _id: "47",
      name: "Kadai Mushroom",
      image: "food_47.jpg",
      price: 160,
      category: "North Indian",
    },
    {
      _id: "48",
      name: "Kaju Masala",
      image: "food_48.jpg",
      price: 200,
      category: "North Indian",
    },
    {
      _id: "49",
      name: "Veg Korma",
      image: "food_49.jpg",
      price: 110,
      category: "North Indian",
    },
    {
      _id: "50",
      name: "Dal Makhani",
      image: "food_50.jpg",
      price: 130,
      category: "North Indian",
    },
    {
      _id: "51",
      name: "Veg Kofta Masala",
      image: "food_51.jpg",
      price: 230,
      category: "North Indian",
    },
    {
      _id: "52",
      name: "Matar Paneer Masala",
      image: "food_52.jpg",
      price: 220,
      category: "North Indian",
    },
    {
      _id: "53",
      name: "Paneer Bhurji",
      image: "food_53.jpg",
      price: 150,
      category: "North Indian",
    },
    {
      _id: "54",
      name: "Butter Paneer Masala",
      image: "food_54.jpg",
      price: 200,
      category: "North Indian",
    },
    {
      _id: "55",
      name: "Veg Kheema",
      image: "food_55.jpg",
      price: 140,
      category: "North Indian",
    },
    {
      _id: "56",
      name: "Veg Mix Masala",
      image: "food_56.jpg",
      price: 160,
      category: "North Indian",
    },
    {
      _id: "57",
      name: "Soya Masala",
      image: "food_57.jpg",
      price: 140,
      category: "North Indian",
    },
    {
      _id: "58",
      name: "Butter Mushroom Masala",
      image: "food_58.jpg",
      price: 170,
      category: "North Indian",
    },
    {
      _id: "59",
      name: "Mushroom Ghee Roast",
      image: "food_59.jpg",
      price: 250,
      category: "North Indian",
    },
    {
      _id: "60",
      name: "Paneer Ghee Roast",
      image: "food_60.jpg",
      price: 270,
      category: "North Indian",
    },
    {
      _id: "61",
      name: "Ghee Rice",
      image: "food_61.jpg",
      price: 100,
      category: "North Indian",
    },
    {
      _id: "62",
      name: "Jeera Rice",
      image: "food_62.jpg",
      price: 80,
      category: "North Indian",
    },
    {
      _id: "63",
      name: "Mushroom Biryani",
      image: "food_63.jpg",
      price: 180,
      category: "North Indian",
    },
    {
      _id: "64",
      name: "Palak Paneer",
      image: "food_64.jpg",
      price: 160,
      category: "North Indian",
    },
    {
      _id: "65",
      name: "Palak Green Rice",
      image: "food_65.jpg",
      price: 120,
      category: "North Indian",
    },
    {
      _id: "66",
      name: "Paneer Biryani",
      image: "food_66.jpg",
      price: 200,
      category: "North Indian",
    },
    {
      _id: "67",
      name: "North Meals",
      image: "food_67.jpg",
      price: 190,
      category: "North Indian",
    },
    {
      _id: "68",
      name: "Singapuri Rice",
      image: "food_68.jpg",
      price: 110,
      category: "North Indian",
    },
    {
      _id: "69",
      name: "Tawa Paneer",
      image: "food_69.jpg",
      price: 190,
      category: "North Indian",
    },
    {
      _id: "70",
      name: "Tawa Pulao",
      image: "food_70.jpg",
      price: 110,
      category: "North Indian",
    },
    {
      _id: "71",
      name: "Veg Biryani",
      image: "food_71.jpg",
      price: 200,
      category: "North Indian",
    },
    {
      _id: "72",
      name: "Baby Manchurian",
      image: "food_72.jpg",
      price: 100,
      category: "Chinese",
    },
    {
      _id: "73",
      name: "Gobi Manchurian",
      image: "food_73.jpg",
      price: 90,
      category: "Chinese",
    },
    {
      _id: "74",
      name: "Mushroom Manchurian",
      image: "food_74.jpg",
      price: 110,
      category: "Chinese",
    },
    {
      _id: "75",
      name: "Veg Manchurian",
      image: "food_75.jpg",
      price: 100,
      category: "Chinese",
    },
    {
      _id: "76",
      name: "Veg Hakka Noodles",
      image: "food_76.jpg",
      price: 80,
      category: "Chinese",
    },
    {
      _id: "77",
      name: "Garlic Rice",
      image: "food_77.jpg",
      price: 90,
      category: "Chinese",
    },
    {
      _id: "78",
      name: "Veg Fried Rice",
      image: "food_78.jpg",
      price: 90,
      category: "Chinese",
    },
    {
      _id: "79",
      name: "Gobi Fried Rice",
      image: "food_79.jpg",
      price: 120,
      category: "Chinese",
    },
    {
      _id: "80",
      name: "Mushroom Noodles",
      image: "food_80.jpg",
      price: 100,
      category: "Chinese",
    },
    {
      _id: "81",
      name: "Schezwan Rice",
      image: "food_81.jpg",
      price: 100,
      category: "Chinese",
    },
    {
      _id: "82",
      name: "Corn Fried Rice",
      image: "food_82.jpg",
      price: 100,
      category: "Chinese",
    },
    {
      _id: "83",
      name: "Garlic Noodles",
      image: "food_83.jpg",
      price: 90,
      category: "Chinese",
    },
    {
      _id: "84",
      name: "Gobi Noodles",
      image: "food_84.jpg",
      price: 120,
      category: "Chinese",
    },
    {
      _id: "85",
      name: "Veg Chowmein",
      image: "food_85.jpg",
      price: 100,
      category: "Chinese",
    },
    {
      _id: "86",
      name: "Paneer Noodles",
      image: "food_86.jpg",
      price: 130,
      category: "Chinese",
    },
    {
      _id: "87",
      name: "Schezwan Noodles",
      image: "food_87.jpg",
      price: 90,
      category: "Chinese",
    },
    {
      _id: "88",
      name: "Corn Noodles",
      image: "food_88.jpg",
      price: 100,
      category: "Chinese",
    },
    {
      _id: "89",
      name: "Mushroom Fried Rice",
      image: "food_89.jpg",
      price: 100,
      category: "Chinese",
    },
    {
      _id: "90",
      name: "Corn Pasta",
      image: "food_90.jpg",
      price: 100,
      category: "Italian",
    },
    {
      _id: "91",
      name: "Fruit Pasta",
      image: "food_91.jpg",
      price: 110,
      category: "Italian",
    },
    {
      _id: "92",
      name: "Veg Macaroni",
      image: "food_92.jpg",
      price: 90,
      category: "Italian",
    },
    {
      _id: "93",
      name: "Masala Pasta",
      image: "food_93.jpg",
      price: 95,
      category: "Italian",
    },
    {
      _id: "94",
      name: "Mushroom Pasta",
      image: "food_94.jpg",
      price: 110,
      category: "Italian",
    },
    {
      _id: "95",
      name: "Pink Sauce Pasta",
      image: "food_95.jpg",
      price: 100,
      category: "Italian",
    },
    {
      _id: "96",
      name: "Pesto Pasta",
      image: "food_96.jpg",
      price: 110,
      category: "Italian",
    },
    {
      _id: "97",
      name: "White Sauce Pasta",
      image: "food_97.jpg",
      price: 110,
      category: "Italian",
    },
    {
      _id: "98",
      name: "Broccoli Pasta",
      image: "food_98.jpg",
      price: 110,
      category: "Italian",
    },
    {
      _id: "99",
      name: "Veg Lasagna",
      image: "food_99.jpg",
      price: 150,
      category: "Italian",
    },
    {
      _id: "100",
      name: "Margherita Pizza",
      image: "food_100.jpg",
      price: 100,
      category: "Italian",
    },
    {
      _id: "101",
      name: "Corn Cheese Pizza",
      image: "food_101.jpg",
      price: 120,
      category: "Italian",
    },
    {
      _id: "102",
      name: "Double Cheese Burst",
      image: "food_102.jpg",
      price: 150,
      category: "Italian",
    },
    {
      _id: "103",
      name: "Mushroom Pizza",
      image: "food_103.jpg",
      price: 140,
      category: "Italian",
    },
    {
      _id: "104",
      name: "Paneer Tikka Pizza",
      image: "food_104.jpg",
      price: 180,
      category: "Italian",
    },
    {
      _id: "105",
      name: "Pineapple Pizza",
      image: "food_105.jpg",
      price: 120,
      category: "Italian",
    },
    {
      _id: "106",
      name: "Veg Mix Pizza",
      image: "food_106.jpg",
      price: 130,
      category: "Italian",
    },
    {
      _id: "107",
      name: "Chilly Mushroom",
      image: "food_107.jpg",
      price: 120,
      category: "Starters",
    },
    {
      _id: "108",
      name: "Chilly Paneer",
      image: "food_108.jpg",
      price: 150,
      category: "Starters",
    },
    {
      _id: "109",
      name: "Chilly Babycorn",
      image: "food_109.jpg",
      price: 120,
      category: "Starters",
    },
    {
      _id: "110",
      name: "Crispy Corn",
      image: "food_110.jpg",
      price: 120,
      category: "Starters",
    },
    {
      _id: "111",
      name: "Soya 65",
      image: "food_111.jpg",
      price: 100,
      category: "Starters",
    },
    {
      _id: "112",
      name: "Honey Chilly Potato",
      image: "food_112.jpg",
      price: 90,
      category: "Starters",
    },
    {
      _id: "113",
      name: "Mushroom 65",
      image: "food_113.jpg",
      price: 120,
      category: "Starters",
    },
    {
      _id: "114",
      name: "Mushroom Pepper Dry",
      image: "food_114.jpg",
      price: 110,
      category: "Starters",
    },
    {
      _id: "115",
      name: "Paneer 65",
      image: "food_115.jpg",
      price: 150,
      category: "Starters",
    },
    {
      _id: "116",
      name: "Mushroom Tikka Masala",
      image: "food_116.jpg",
      price: 180,
      category: "Starters",
    },
    {
      _id: "117",
      name: "Paneer Tikka Masala",
      image: "food_117.jpg",
      price: 200,
      category: "Starters",
    },
    {
      _id: "118",
      name: "Hot and Sour Soup",
      image: "food_118.jpg",
      price: 70,
      category: "Starters",
    },
    {
      _id: "119",
      name: "Veg Manchow Soup",
      image: "food_119.jpg",
      price: 80,
      category: "Starters",
    },
    {
      _id: "120",
      name: "Pumpkin Soup",
      image: "food_120.jpg",
      price: 60,
      category: "Starters",
    },
    {
      _id: "121",
      name: "Tomato Soup",
      image: "food_121.jpg",
      price: 50,
      category: "Starters",
    },
    {
      _id: "122",
      name: "Sweet Corn Soup",
      image: "food_122.jpg",
      price: 70,
      category: "Starters",
    },
    {
      _id: "123",
      name: "Bhel Puri",
      image: "food_123.jpg",
      price: 40,
      category: "Snacks",
    },
    {
      _id: "124",
      name: "Dahi Puri",
      image: "food_124.jpg",
      price: 50,
      category: "Snacks",
    },
    {
      _id: "125",
      name: "Raj Kachori",
      image: "food_125.jpg",
      price: 60,
      category: "Snacks",
    },
    {
      _id: "126",
      name: "Masala Puri",
      image: "food_126.jpg",
      price: 45,
      category: "Snacks",
    },
    {
      _id: "127",
      name: "Pani Puri",
      image: "food_127.jpg",
      price: 40,
      category: "Snacks",
    },
    {
      _id: "128",
      name: "Dahi Kebab",
      image: "food_128.jpg",
      price: 70,
      category: "Snacks",
    },
    {
      _id: "129",
      name: "Dahi Bhalla",
      image: "food_129.jpg",
      price: 60,
      category: "Snacks",
    },
    {
      _id: "130",
      name: "Aloo Samosa",
      image: "food_130.jpg",
      price: 30,
      category: "Snacks",
    },
    {
      _id: "131",
      name: "Onion Samosa",
      image: "food_131.jpg",
      price: 30,
      category: "Snacks",
    },
    {
      _id: "132",
      name: "Vada Pav",
      image: "food_132.jpg",
      price: 40,
      category: "Snacks",
    },
    {
      _id: "133",
      name: "Sev Puri",
      image: "food_133.jpg",
      price: 50,
      category: "Snacks",
    },
    {
      _id: "134",
      name: "Veg Cutlet",
      image: "food_134.jpg",
      price: 60,
      category: "Snacks",
    },
    {
      _id: "135",
      name: "Pav Bhaji",
      image: "food_135.jpg",
      price: 100,
      category: "Snacks",
    },
    {
      _id: "136",
      name: "Dhokla",
      image: "food_136.jpg",
      price: 50,
      category: "Snacks",
    },
    {
      _id: "137",
      name: "Pakora",
      image: "food_137.jpg",
      price: 40,
      category: "Snacks",
    },
    {
      _id: "138",
      name: "Veg Cheese burger",
      image: "food_138.jpg",
      price: 90,
      category: "Snacks",
    },
    {
      _id: "139",
      name: "Veg Burger",
      image: "food_139.jpg",
      price: 80,
      category: "Snacks",
    },
    {
      _id: "140",
      name: "Aloo Tikki",
      image: "food_140.jpg",
      price: 40,
      category: "Snacks",
    },
    {
      _id: "141",
      name: "Bread Pakora",
      image: "food_141.jpg",
      price: 40,
      category: "Snacks",
    },
    {
      _id: "142",
      name: "Veg Lollipop",
      image: "food_142.jpg",
      price: 100,
      category: "Snacks",
    },
    {
      _id: "143",
      name: "Potato Nuggets",
      image: "food_143.jpg",
      price: 90,
      category: "Snacks",
    },
    {
      _id: "144",
      name: "Veg Kebab",
      image: "food_144.jpg",
      price: 90,
      category: "Snacks",
    },
    {
      _id: "145",
      name: "Harabara Kebab",
      image: "food_145.jpg",
      price: 100,
      category: "Snacks",
    },
    {
      _id: "146",
      name: "Cheese Balls",
      image: "food_146.jpg",
      price: 70,
      category: "Snacks",
    },
    {
      _id: "147",
      name: "Veg Cheese Roll",
      image: "food_147.jpg",
      price: 65,
      category: "Snacks",
    },
    {
      _id: "148",
      name: "Aloo Masala Roll",
      image: "food_148.jpg",
      price: 55,
      category: "Snacks",
    },
    {
      _id: "149",
      name: "Palak Green Roll",
      image: "food_149.jpg",
      price: 60,
      category: "Snacks",
    },
    {
      _id: "150",
      name: "Mushroom Masala Rolls",
      image: "food_150.jpg",
      price: 80,
      category: "Snacks",
    },
    {
      _id: "151",
      name: "Paneer Tikka Roll",
      image: "food_151.jpg",
      price: 120,
      category: "Snacks",
    },
    {
      _id: "152",
      name: "Paneer Masala Roll",
      image: "food_152.jpg",
      price: 100,
      category: "Snacks",
    },
    {
      _id: "153",
      name: "Veg Kheema Roll",
      image: "food_153.jpg",
      price: 90,
      category: "Snacks",
    },
    {
      _id: "154",
      name: "Veg Spring Roll",
      image: "food_154.jpg",
      price: 60,
      category: "Snacks",
    },
    {
      _id: "155",
      name: "Veg Nuggets",
      image: "food_155.jpg",
      price: 100,
      category: "Snacks",
    },
    {
      _id: "156",
      name: "French Fries",
      image: "food_156.jpg",
      price: 50,
      category: "Snacks",
    },
    {
      _id: "157",
      name: "Garlic Bread",
      image: "food_157.jpg",
      price: 70,
      category: "Snacks",
    },
    {
      _id: "158",
      name: "Paneer Sandwich",
      image: "food_158.jpg",
      price: 90,
      category: "Snacks",
    },
    {
      _id: "159",
      name: "Veg Sandwich",
      image: "food_159.jpg",
      price: 60,
      category: "Snacks",
    },
    {
      _id: "160",
      name: "Veg Grill Sandwich",
      image: "food_160.jpg",
      price: 70,
      category: "Snacks",
    },
    {
      _id: "161",
      name: "Double Cheese Grilled Sandwich",
      image: "food_161.jpg",
      price: 85,
      category: "Snacks",
    },
    {
      _id: "162",
      name: "Sweet Corn Sandwich",
      image: "food_162.jpg",
      price: 70,
      category: "Snacks",
    },
    {
      _id: "163",
      name: "Mushroom Sandwich",
      image: "food_163.jpg",
      price: 80,
      category: "Snacks",
    },
    {
      _id: "164",
      name: "Dahi Sandwich",
      image: "food_164.jpg",
      price: 80,
      category: "Snacks",
    },
    {
      _id: "165",
      name: "Cheesy Garlic Bread",
      image: "food_165.jpg",
      price: 90,
      category: "Snacks",
    },
    {
      _id: "166",
      name: "Apple Juice",
      image: "food_166.jpg",
      price: 60,
      category: "Beverages",
    },
    {
      _id: "167",
      name: "Black Grape Juice",
      image: "food_167.jpg",
      price: 50,
      category: "Beverages",
    },
    {
      _id: "168",
      name: "Green Grape Juice",
      image: "food_168.jpg",
      price: 40,
      category: "Beverages",
    },
    {
      _id: "169",
      name: "Lemon Juice",
      image: "food_169.jpg",
      price: 20,
      category: "Beverages",
    },
    {
      _id: "170",
      name: "Mosambi Juice",
      image: "food_170.jpg",
      price: 30,
      category: "Beverages",
    },
    {
      _id: "171",
      name: "Orange Juice",
      image: "food_171.jpg",
      price: 40,
      category: "Beverages",
    },
    {
      _id: "172",
      name: "Pineapple Juice",
      image: "food_172.jpg",
      price: 35,
      category: "Beverages",
    },
    {
      _id: "173",
      name: "Pomegranate Juice",
      image: "food_173.jpg",
      price: 60,
      category: "Beverages",
    },
    {
      _id: "174",
      name: "Watermelon Juice",
      image: "food_174.jpg",
      price: 30,
      category: "Beverages",
    },
    {
      _id: "175",
      name: "Avocado Milkshake",
      image: "food_175.jpg",
      price: 80,
      category: "Beverages",
    },
    {
      _id: "176",
      name: "Banana Milkshake",
      image: "food_176.jpg",
      price: 50,
      category: "Beverages",
    },
    {
      _id: "177",
      name: "Chikoo Milkshake",
      image: "food_177.jpg",
      price: 50,
      category: "Beverages",
    },
    {
      _id: "178",
      name: "Mango Milkshake",
      image: "food_178.jpg",
      price: 80,
      category: "Beverages",
    },
    {
      _id: "179",
      name: "Muskmelon Milkshake",
      image: "food_179.jpg",
      price: 50,
      category: "Beverages",
    },
    {
      _id: "180",
      name: "Anjeer Milkshake",
      image: "food_180.jpg",
      price: 90,
      category: "Beverages",
    },
    {
      _id: "181",
      name: "Papaya Milkshake",
      image: "food_181.jpg",
      price: 50,
      category: "Beverages",
    },
    {
      _id: "182",
      name: "Tea",
      image: "food_182.jpg",
      price: 20,
      category: "Beverages",
    },
    {
      _id: "183",
      name: "Strawberry Milkshake",
      image: "food_183.jpg",
      price: 80,
      category: "Beverages",
    },
    {
      _id: "184",
      name: "Vanilla Milkshake",
      image: "food_184.jpg",
      price: 60,
      category: "Beverages",
    },
    {
      _id: "185",
      name: "Dry Fruit Milkshake",
      image: "food_185.jpg",
      price: 120,
      category: "Beverages",
    },
    {
      _id: "186",
      name: "Chocolate Milkshake",
      image: "food_186.jpg",
      price: 60,
      category: "Beverages",
    },
    {
      _id: "187",
      name: "Black Coffee",
      image: "food_187.jpg",
      price: 30,
      category: "Beverages",
    },
    {
      _id: "188",
      name: "Black Tea",
      image: "food_188.jpg",
      price: 25,
      category: "Beverages",
    },
    {
      _id: "189",
      name: "Blue Tea",
      image: "food_189.jpg",
      price: 35,
      category: "Beverages",
    },
    {
      _id: "190",
      name: "Filter Coffee",
      image: "food_190.jpg",
      price: 30,
      category: "Beverages",
    },
    {
      _id: "191",
      name: "Green Tea",
      image: "food_191.jpg",
      price: 30,
      category: "Beverages",
    },
    {
      _id: "192",
      name: "Lemon Tea",
      image: "food_192.jpg",
      price: 30,
      category: "Beverages",
    },
    {
      _id: "193",
      name: "White Tea",
      image: "food_193.jpg",
      price: 40,
      category: "Beverages",
    },
    {
      _id: "194",
      name: "Cold Coffee",
      image: "food_194.jpg",
      price: 50,
      category: "Beverages",
    },
    {
      _id: "195",
      name: "Choco Cold Coffee",
      image: "food_195.jpg",
      price: 60,
      category: "Beverages",
    },
    {
      _id: "196",
      name: "Badam Milk",
      image: "food_196.jpg",
      price: 60,
      category: "Beverages",
    },
    {
      _id: "197",
      name: "Rose Milk",
      image: "food_197.jpg",
      price: 50,
      category: "Beverages",
    },
    {
      _id: "198",
      name: "Buttermilk",
      image: "food_198.jpg",
      price: 20,
      category: "Beverages",
    },
    {
      _id: "199",
      name: "Masala Buttermilk",
      image: "food_199.jpg",
      price: 25,
      category: "Beverages",
    },
    {
      _id: "200",
      name: "Sweet Lassi",
      image: "food_200.jpg",
      price: 30,
      category: "Beverages",
    },
    {
      _id: "201",
      name: "Masala Tea",
      image: "food_201.jpg",
      price: 30,
      category: "Beverages",
    },
    {
      _id: "202",
      name: "Black Forest",
      image: "food_202.jpg",
      price: 70,
      category: "Desserts",
    },
    {
      _id: "203",
      name: "Choco Truffle",
      image: "food_203.jpg",
      price: 80,
      category: "Desserts",
    },
    {
      _id: "204",
      name: "White Forest",
      image: "food_204.jpg",
      price: 70,
      category: "Desserts",
    },
    {
      _id: "205",
      name: "Red Velvet",
      image: "food_205.jpg",
      price: 85,
      category: "Desserts",
    },
    {
      _id: "206",
      name: "Chocolate Ice Cream",
      image: "food_206.jpg",
      price: 40,
      category: "Desserts",
    },
    {
      _id: "207",
      name: "Vanilla Ice Cream",
      image: "food_207.jpg",
      price: 35,
      category: "Desserts",
    },
    {
      _id: "208",
      name: "Strawberry Ice Cream",
      image: "food_208.jpg",
      price: 40,
      category: "Desserts",
    },
    {
      _id: "209",
      name: "Fruit Salad with Ice Cream",
      image: "food_209.jpg",
      price: 90,
      category: "Desserts",
    },
    {
      _id: "210",
      name: "Fruit Salad",
      image: "food_210.jpg",
      price: 70,
      category: "Desserts",
    },
    {
      _id: "211",
      name: "Gudbud",
      image: "food_211.jpg",
      price: 80,
      category: "Desserts",
    },
    {
      _id: "212",
      name: "Fruit Sandwich",
      image: "food_212.jpg",
      price: 60,
      category: "Desserts",
    },
    {
      _id: "213",
      name: "Mango Ice Cream",
      image: "food_213.jpg",
      price: 50,
      category: "Desserts",
    },
    {
      _id: "214",
      name: "Obbattu",
      image: "food_214.jpg",
      price: 60,
      category: "Desserts",
    },
    {
      _id: "215",
      name: "Mysore Pak",
      image: "food_215.jpg",
      price: 35,
      category: "Desserts",
    },
    {
      _id: "216",
      name: "Payasa",
      image: "food_216.jpg",
      price: 40,
      category: "Desserts",
    },
    {
      _id: "217",
      name: "Carrot Halwa",
      image: "food_217.jpg",
      price: 30,
      category: "Desserts",
    },
    {
      _id: "218",
      name: "Cham Cham",
      image: "food_218.jpg",
      price: 50,
      category: "Desserts",
    },
    {
      _id: "219",
      name: "Dharwad Peda",
      image: "food_219.jpg",
      price: 45,
      category: "Desserts",
    },
    {
      _id: "220",
      name: "Gulab Jamoon",
      image: "food_220.jpg",
      price: 60,
      category: "Desserts",
    },
    {
      _id: "221",
      name: "Jalebi",
      image: "food_221.jpg",
      price: 30,
      category: "Desserts",
    },
    {
      _id: "222",
      name: "Kaju Barfi",
      image: "food_222.jpg",
      price: 50,
      category: "Desserts",
    },
    {
      _id: "223",
      name: "Kheer",
      image: "food_223.jpg",
      price: 40,
      category: "Desserts",
    },
    {
      _id: "224",
      name: "Ladoo",
      image: "food_224.jpg",
      price: 25,
      category: "Desserts",
    },
    {
      _id: "225",
      name: "Peda",
      image: "food_225.jpg",
      price: 30,
      category: "Desserts",
    },
    {
      _id: "226",
      name: "Rasagolla",
      image: "food_226.jpg",
      price: 60,
      category: "Desserts",
    },
    {
      _id: "227",
      name: "Rasamalai",
      image: "food_227.jpg",
      price: 80,
      category: "Desserts",
    },
  ];

  // Function to group items by category
  // Group items by category
  const categorizedItems = foodItems.reduce((acc, item) => {
    if (!acc[item.category]) {
      acc[item.category] = [];
    }
    acc[item.category].push(item);
    return acc;
  }, {});

  return (
    <div className="menu-card">
      <h1 className="menu-title">Bhojanalaya Menu</h1>
      {Object.keys(categorizedItems).map((category) => (
        <div key={category} className="category-section">
          <h2 className="category-title">{category}</h2>
          {categorizedItems[category].map((item) => (
            <div key={item.id} className="menu-item">
              <div className="menu-item-details">
                <h3 className="menu-item-name">{item.name}</h3>
                <p className="menu-item-price">₹{item.price}</p>
              </div>
            </div>
          ))}
        </div>
      ))}
    </div>
  );
};

export default Menucard;
